version: '3'
services:
  backend:
    build: ./raised-hands-server/
    container_name: raised-hands-server
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - "8000"
    networks:
      - main

networks:
  main: