version: '3'
services:
  backend:
    build:
      context: ./raised-hands-server/
      dockerfile: Dockerfile.dev
    container_name: raised-hands-server
    command: ["gradle", "bootRun", "--args='--spring.profiles.active=dev'"]
    restart: on-failure
    volumes:
      - ./raised-hands-server:/app
    ports:
      - "5005:5005"
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - main
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_DDL_AUTO
      - CLOUD_SQL_DB_NAME
      - CLOUD_SQL_INSTANCE_CONNECTION_NAME
      - CLOUD_SQL_PROJECT_ID
      - CLOUD_CREDENTIALS_FILE
      - SECURITY_SECRET_KEY
      - SECURITY_EXPIRATION_TIME
      - SECURITY_TOKEN_PREFIX
      - SECURITY_HEADER_STRING
    depends_on:
      - db

  frontend:
    build:
      context: ./raised-hands-web-client/
      dockerfile: Dockerfile.dev
    container_name: raised-hands-web-client
    command: ["npm", "start"]
    restart: on-failure
    volumes:
      - ./raised-hands-web-client:/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - main
    environment:
      - REACT_APP_API_URL
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - main
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

networks:
  main:
